# Generated by Django 4.2.1 on 2023-05-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tech",
            name="url",
            field=models.URLField(max_length=450),
        ),
    ]
