# Generated by Django 4.2.1 on 2023-05-12 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("techs", "0004_alter_tech_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(default=None, null=True)),
                ("repository", models.URLField(max_length=9999, unique=True)),
                ("link_deploy", models.URLField(max_length=9999)),
                ("img", models.URLField(max_length=9999)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "techs",
                    models.ManyToManyField(related_name="projects", to="techs.tech"),
                ),
            ],
        ),
    ]
